<?php

declare(strict_types=1);

namespace Marktic\Newsletter\Bundle\Controllers\Admin;

use Marktic\Newsletter\Bundle\Controllers\Base\Behaviours\HasNewsletterOwnerTrait;
use Marktic\Newsletter\NewsletterOwners\Dto\NewsletterOwner;
use Marktic\Newsletter\Subscriptions\Actions\Reports\BuildCompleteSubscriptionsReport;
use Marktic\Newsletter\Utility\NewsletterModels;
use Nip\Controllers\Response\ResponsePayload;

/**
 * @method ResponsePayload payload()
 */
trait SubscriptionsControllerTrait
{
    use HasNewsletterOwnerTrait;

    public function export()
    {
        BuildCompleteSubscriptionsReport::fromRequestFilters($this->getRequestFilters())
            ->render();
    }

    protected function indexPrepareItems($items)
    {
        parent::indexPrepareItems($items);
        $items->loadRelation(NewsletterModels::subscriptions()::RELATION_CONTACT);
        $items->loadRelation(NewsletterModels::subscriptions()::RELATION_LIST);
        $items->loadRelation(NewsletterModels::subscriptions()::RELATION_CONSENT_ARTIFACTS);
    }

    protected function parseRequest()
    {
        parent::parseRequest(); // TODO: Change the autogenerated stub

        $this->getRequest()->setAttribute(NewsletterOwner::CONTROLLER_ATTRIBUTE,$this->getNewsletterOwner());
    }
}
